swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger petstore
  description: A sample API that demonstrates Swagger-Express-Middleware features

host: petstore.swagger.io:8000
basePath: /api

consumes:
  - application/json
produces:
  - application/json

definitions:
  pet:
    $ref: definitions/pet.yaml

  veterinarian:
    $ref: definitions/veterinarian.yaml

  address:
    $ref: definitions/address.yaml

parameters:
  petName:
    name: petName
    in: path
    description: Name of the pet
    required: true
    type: string

paths:
  /pets:
    get:
      $ref: operations/pets/get.yaml

    post:
      $ref: operations/pets/post.yaml

    delete:
      $ref: operations/pets/delete.yaml

  /pets/{petName}:
    parameters:
      - $ref: "#/parameters/petName"

    get:
      $ref: operations/pet/get.yaml

    delete:
      $ref: operations/pet/delete.yaml

    patch:
      $ref: operations/pet/patch.yaml

  /pets/{petName}/photos:
    parameters:
      - $ref: "#/parameters/petName"

    post:
      $ref: operations/photos/post.yaml

    get:
      $ref: operations/photos/get.yaml

  /pets/{petName}/photos/{id}:
    parameters:
      - $ref: "#/parameters/petName"
      - name: id
        in: path
        description: The ID of the photo
        required: true
        type: integer
        format: int32

    get:
      $ref: operations/photo/get.yaml

    delete:
      $ref: operations/photo/delete.yaml

  /:
    get:
      $ref: operations/root/get.yaml
