- name: tags
  in: query
  description: Filters pets by one or more tags
  required: false
  type: array
  items:
    type: string
  uniqueItems: true
  collectionFormat: csv
- name: type
  in: query
  description: Filters pets by type (dog, cat, or bird)
  required: false
  type: string
  enum: [cat, dog, bird]
- name: age
  in: query
  description: Filters pets by age
  required: false
  type: integer
- name: dob
  in: query
  description: Filters pets by date of birth
  required: false
  type: string
  format: date
- name: address.city
  in: query
  description: Filters pets by city
  required: false
  type: string
- name: address.state
  in: query
  description: Filters pets by state
  required: false
  type: string
- name: address.zipcode
  in: query
  description: Filters pets by zip code
  required: false
  type: integer
- name: vet.name
  in: query
  description: Filters pets by veterinarian name
  required: false
  type: string
- name: vet.address.city
  in: query
  description: Filters pets by veterinarian city
  required: false
  type: string
- name: vet.address.state
  in: query
  description: Filters pets by veterinarian state
  required: false
  type: string
- name: vet.address.zipcode
  in: query
  description: Filters pets by veterinarian zip code
  required: false
  type: integer
