swagger: "2.0"
info:
  version: "1.0.0"
  title: minimal
  description: Example of the bare minimum Swagger spec
host: localhost:3000 # otherwise, a random port will be used each time
paths:
  /users:
    get:
      responses:
        "200":
          description:  Describe the 200 response in more detail
